'use client';

import { DnDProvider } from '@/context/DnDContextProvider';
import { useDragAndDrop } from '@/hooks/useDragAndDrop';
import Head from 'next/head';
import { useState } from 'react';
import DraggableBoard from './_components/DraggableBoard';

export default function DnD() {
  return (
    <>
      <Head>
        <title>Retro App - Draggable</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DnDProvider>
        <DraggableBoard />
      </DnDProvider>
    </>
  );
}
