'use client';

import { DnDProvider } from '@/context/DnDContextProvider';
import { useDragAndDrop } from '@/hooks/useDnD';
import Head from 'next/head';
import { useState } from 'react';
import DraggableBoard from './_components/DraggableBoard';

export default function DnD() {
  const [dropZones, setDropZones] = useState([{ id: 'dz_1' }, { id: 'dz_2' }, { id: 'dz_3' }]);
  const { cards } = useDragAndDrop();

  console.log('cards', cards);

  return (
    <>
      <Head>
        <title>Retro App - Draggable</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DnDProvider>
        <DraggableBoard />
      </DnDProvider>
    </>
  );
}
